apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-web
  namespace: {{ .Values.namespace }}
  labels:
    app: python-web
    {{- include "python-demo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app: python-web
  template:
    metadata:
      labels:
        app: python-web
    spec:
      containers:
        - name: web
          image: {{ .Values.web.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.web.port }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.web.port }}
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.web.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 250m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
