apiVersion: v1
kind: Service
metadata:
  name: python-web
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.web.serviceType }}
  selector:
    app: python-web
  ports:
    - protocol: TCP
      port: {{ .Values.web.servicePort }}
      targetPort: {{ .Values.web.port }}
